### PR TITLE
Make selected rows also highlight on hover + color tweaks

### PR DESCRIPTION
**Pull request by iliaross**

### CODE REVIEW

**Comment by iliaross** [comment]
Besides I think it makes sense to make only for table body:

``` CSS
#list_form tbody tr.checked:hover,
#list_form tbody tr:hover {
    background: #d3e4f4 !important;
}
```

**Comment by Real-Gecko** [comment]
So do I merge, or shall I take changes from you comment?

**Comment by iliaross** [comment]
Do from comments, its always easier.

**Comment by Real-Gecko** [comment]
Crap, I've already made new release, your fix will go to new one :)))

**Comment by iliaross** [comment]
ok!

**Pull request closed without merging**
